language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      cache: apt
      dist: xenial

env:
  global:
    - PROJECT_NAME=PortaPack-HackRF
    - SHORT_COMMIT_HASH=`git rev-parse --short HEAD`
    - VERSION_STRING=nightly-$SHORT_COMMIT_HASH
    - BUILD_NAME="$PROJECT_NAME-`date +%Y-%m-%d`-$SHORT_COMMIT_HASH"
    - ARTEFACT_BASE=$TRAVIS_BUILD_DIR/artefacts/
    - ARTEFACT_PATH=$ARTEFACT_BASE/$BUILD_NAME

notifications:
  irc:
    channels:
      - "chat.freenode.net#portapack"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      # TODO: The "build_number.1" in this URL is almost certainly wrong, but correct value not available from Travis?
      - "Firmware download : https://portapack-h1-builds.s3.amazonaws.com/%{repository_slug}/%{build_number}/%{build_number}.1/build/firmware/portapack-h1-firmware-%{commit}.tar.bz2"

before_install:
  - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-arm-embedded -y

script:
  # TODO: Introduce top-level Makefile, this is lame.
  - sed -e "s/\#set(VERSION.*/set(VERSION \"$VERSION_STRING\")/" -i".bak" CMakeLists.txt
  - mkdir build/
  - pushd build/
  - cmake ..
  - make firmware
  - popd

after_success:
  - mkdir -p $ARTEFACT_PATH
  # Copy firmware to firmware-bin directory
  - cd $TRAVIS_BUILD_DIR/firmware
  - cp build/firmware/portapack-h1-firmware.bin $ARTEFACT_PATH/
  - cp build/firmware/hackrf-prefix/src/hackrf-build/hackrf_usb/hackrf_usb.dfu $ARTEFACT_PATH/
  - cp LICENSE $ARTEFACT_PATH/
  # Build the archive
  - cd $ARTEFACT_BASE
  - tar -cJvf $ARTEFACT_BASE/$BUILD_NAME.tar.xz $BUILD_NAME
  - md5sum --binary $ARTEFACT_BASE/$BUILD_NAME.tar.xz >MD5SUMS
  - sha256sum --binary $ARTEFACT_BASE/$BUILD_NAME.tar.xz >SHA256SUMS

addons:
  apt:
    packages:
      - coreutils
      - tar
      - sed
      - cmake
      - gcc-arm-none-eabi
      - dfu-util

deploy:
  provider: script
  skip-cleanup: true
  script: bash $TRAVIS_BUILD_DIR/tools/deploy-nightly.sh
  on:
    branch: master
